default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: cb_dev

test:
  <<: *default
  database: cb_test

production:
  <<: *default
  database: cb_prod
